parkingdemo:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Effort Controllers ---------------------------------------
  rr_Wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_rr_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  rl_Wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_rl_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  fr_Wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_fr_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  fl_Wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_fl_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  # Position Controllers ---------------------------------------
  fr_Steer_position_controller:
    type: effort_controllers/JointPositionController
    joint: steer_fr_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  fl_Steer_position_controller:
    type: effort_controllers/JointPositionController
    joint: steer_fl_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}
